/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.superbank;

import static org.junit.Assert.assertEquals;
import static spark.Spark.awaitInitialization;

import java.io.IOException;

import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;


public class TransactionManagerTest {
	
    private CloseableHttpClient httpClient;
    
    @Before
    public void setup() {
    	httpClient = HttpClients.createDefault();
    	TransactionManager.main(null);
        awaitInitialization();
    }
    
	@Test public void testGetAccount() throws ClientProtocolException, IOException {
        HttpGet request = new HttpGet("http://localhost:4567/account/123");

        try (CloseableHttpResponse response = httpClient.execute(request)) {
        	assertEquals("HTTP/1.1 200 OK", response.getStatusLine().toString());
        }
    }
	
	@After
	public void teardown() throws IOException {
		httpClient.close();
	}
}
