/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.superbank;

import static spark.Spark.before;
import static spark.Spark.get;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.superbank.controller.AccountController;

public class TransactionManager {
	

	private static final Logger LOGGER = LogManager.getLogger(TransactionManager.class);
	
	public static void main(String[] args) {
		
		AccountController accountController = new AccountController();
		
		LOGGER.info("START");
		
	    before("/*", (request, response) -> LOGGER.info("Received API call to path: " + request.uri()));
	    
        get("/account/:accountNumber", (request, response) -> {
        	return accountController.getAccount(request.params("accountNumber"));
        });
    }
    
}
